services:
  jellyfin:
    image: jellyfin/jellyfin:10.11
    container_name: jellyfin
    restart: unless-stopped

    environment:
      TZ: ${TZ:-America/New_York}
      JELLYFIN_PublishedServerUrl: ${JELLYFIN_PUBLISHED_SERVER_URL}

    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined

    ports:
      - "8096:8096"
      - "8920:8920"

    volumes:
      - ${MEDIA_CONFIG_ROOT}/jellyfin/config:/config
      - ${MEDIA_CONFIG_ROOT}/jellyfin/cache:/cache
      - ${TV_ROOT}/Videos:/tv
      - ${MOVIES_ROOT}/videos:/moviess

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command:
      - tunnel
      - --no-autoupdate
      - run
      - --token
      - ${CLOUDFLARED_TOKEN}
    depends_on:
      - jellyfin

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MEDIA_CONFIG_ROOT}/sonarr:/config
      - ${TV_ROOT}:/tv
    ports:
      - "8989:8989"